name:                 a1
version:              1.0.0.0
visibility:           public
id:                   a1-1.0.0.0-inplace
key:                  a1-1.0.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      APL.AST APL.AST_Tests APL.Eval APL.Eval_Tests
import-dirs:
    /mnt/c/Users/marcu/Desktop/AP_assignments/a1/a1-handout/a1-handout/dist-newstyle/build/aarch64-linux/ghc-9.10.3/a1-1.0.0.0/build

library-dirs:
    /mnt/c/Users/marcu/Desktop/AP_assignments/a1/a1-handout/a1-handout/dist-newstyle/build/aarch64-linux/ghc-9.10.3/a1-1.0.0.0/build

library-dirs-static:
    /mnt/c/Users/marcu/Desktop/AP_assignments/a1/a1-handout/a1-handout/dist-newstyle/build/aarch64-linux/ghc-9.10.3/a1-1.0.0.0/build

dynamic-library-dirs:
    /mnt/c/Users/marcu/Desktop/AP_assignments/a1/a1-handout/a1-handout/dist-newstyle/build/aarch64-linux/ghc-9.10.3/a1-1.0.0.0/build

data-dir:
    /mnt/c/Users/marcu/Desktop/AP_assignments/a1/a1-handout/a1-handout/.

hs-libraries:         HSa1-1.0.0.0-inplace
depends:
    base-4.20.2.0-3f0e
    tasty-1.5.4-41bad900bc3c353e2644baf7c2bc7d271eee346909c18a500ad0a08ddef892c7
    tasty-hunit-0.10.2-820bf45e5f904d015d1236d54ede03c147186adb37990e92eeaed72282c0fc1f

haddock-interfaces:
    /mnt/c/Users/marcu/Desktop/AP_assignments/a1/a1-handout/a1-handout/dist-newstyle/build/aarch64-linux/ghc-9.10.3/a1-1.0.0.0/doc/html/a1/a1.haddock

haddock-html:
    /mnt/c/Users/marcu/Desktop/AP_assignments/a1/a1-handout/a1-handout/dist-newstyle/build/aarch64-linux/ghc-9.10.3/a1-1.0.0.0/doc/html/a1
