name:                 a3
version:              1.0.0.0
visibility:           public
id:                   a3-1.0.0.0-inplace
key:                  a3-1.0.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:      APL.AST APL.Eval APL.Parser APL.Parser_Tests
import-dirs:
    /mnt/c/Users/Marcus/Desktop/AP_assignments/a3/dist-newstyle/build/x86_64-linux/ghc-9.10.3/a3-1.0.0.0/build

library-dirs:
    /mnt/c/Users/Marcus/Desktop/AP_assignments/a3/dist-newstyle/build/x86_64-linux/ghc-9.10.3/a3-1.0.0.0/build

library-dirs-static:
    /mnt/c/Users/Marcus/Desktop/AP_assignments/a3/dist-newstyle/build/x86_64-linux/ghc-9.10.3/a3-1.0.0.0/build

dynamic-library-dirs:
    /mnt/c/Users/Marcus/Desktop/AP_assignments/a3/dist-newstyle/build/x86_64-linux/ghc-9.10.3/a3-1.0.0.0/build

data-dir:             /mnt/c/Users/Marcus/Desktop/AP_assignments/a3/.
hs-libraries:         HSa3-1.0.0.0-inplace
depends:
    base-4.20.2.0-f074
    megaparsec-9.8.1-3529298dce5b00df4dbce67afb03aa87fa5a46ef91a3f5aee7a290c180fbd14d
    tasty-1.5.4-60f26347e4e601c0616cabff8476907c933b466a3317ae086c70675b15e5c3d0
    tasty-hunit-0.10.2-2c3f1a2b583880e34a9c3ada6501b5975ccfbac8497789ba736e5a0ae97cc2d2

haddock-interfaces:
    /mnt/c/Users/Marcus/Desktop/AP_assignments/a3/dist-newstyle/build/x86_64-linux/ghc-9.10.3/a3-1.0.0.0/doc/html/a3/a3.haddock

haddock-html:
    /mnt/c/Users/Marcus/Desktop/AP_assignments/a3/dist-newstyle/build/x86_64-linux/ghc-9.10.3/a3-1.0.0.0/doc/html/a3
